url: jdbc:mysql://sql3.minestrator.com/minesr_SagOLEz2?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true
host: sql3.minestrator.com
database: minesr_SagOLEz2
login: minesr_SagOLEz2
pwd: fpuDFFZVf7lhnjb8
loggerUrl: https://canary.discord.com/api/webhooks/1116382641223127120/1Vdpy223HaD8_iL-vgrKaSa3ozO7vOFBXlCLt97FszLh6OnQsjNfUIgeAUhL0LAIlUx6