buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://jitpack.io/" }
        maven { url 'https://m2.dv8tion.net/releases' }
        jcenter()
    }
    dependencies {
        classpath 'com.github.jengelman.gradle.plugins:shadow:2.0.4'
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '3.+', changing: true
    }

}
repositories {
    mavenCentral()
    maven {
        url 'https://m2.dv8tion.net/releases'
    }
    maven{
        name = "CurseForge"
        url = "https://minecraft.curseforge.com/api/maven/"
    }

    maven {
        url('http://maven.dynamx.fr/artifactory/DynamXRepo/')
    }
    maven {
        url 'https://maven.dynamx.fr/artifactory/' + 'ACsGuisRepo/'
    }
    maven {
        url 'https://www.cursemaven.com/'
    }
    maven {
        name = "DragonForge"
        url = "https://maven.zeith.org"
    }
    maven {
        url 'https://m2.dv8tion.net/releases'
    }
}
apply plugin: 'net.minecraftforge.gradle'
apply plugin: "java"
apply plugin: 'idea'
apply plugin: 'com.github.johnrengelman.shadow'

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}

sourceSets { main { output.resourcesDir = output.classesDir } }

version = '1.5.6-rev2'
group = 'fr.yan36.westerlife' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = 'westerlife'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.


minecraft {

    mappings channel: 'stable', version: '39-1.12'

    runs {
        client {
            workingDirectory project.file('WesterLife')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                jw {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('WesterLife')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                jw {
                    source sourceSets.main
                }
            }
        }
    }


    repositories {
        jcenter()
    }

    sourceSets.main.resources { srcDir 'src/generated/resources' }

    dependencies {
        minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'


        implementation fg.deobf('fr.dynamx:DynamX:4.0.0-beta-18')
        implementation "fr.aym.acsguis:ACsGuis:1.2.5"
        implementation fileTree(dir: 'libs', include: '*.jar')

        shadow fileTree(dir: 'libs', include: '*.jar')


        implementation 'com.sedmelluq:lavaplayer:1.3.78'
        implementation 'com.sedmelluq:lava-common:1.1.2'

        shadow 'com.sedmelluq:lavaplayer:1.3.78'
//        shadow 'com.sedmelluq:lava-common:1.1.2'
//        shadow 'org.apache.httpcomponents:httpclient:4.5.13'
//        shadow implementation('org.apache.httpcomponents:httpcore:4.4.14')


        compile 'com.zaxxer:HikariCP:3.1.0'
        compile 'org.slf4j:slf4j-api:1.7.25'
        compile 'mysql:mysql-connector-java:8.0.19'


    }

    repositories {
        flatDir {
            dirs 'libs'
        }
    }

    jar {
        manifest {
            attributes([
                    "Specification-Title"     : "westerlife",
                    "Specification-Vendor"    : "yan36,MK_16,gabidut76",
                    "Specification-Version"   : "2", // We are version 1 of ourselves
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.version,
                    "Implementation-Vendor"   : "MK, Afhistos",
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),

            ])
        }
        from {
            configurations.compile
                    .filter {
                        it.name == 'java-discord-rpc-2.0.1.jar' ||
                        it.name == 'mcef-1.12.2-1.32.jar' ||
                        it.name == 'HikariCP-3.1.0.jar' ||
                        it.name == 'slf4j-api-1.7.25.jar' ||
                        it.name == 'mysql-connector-java-8.0.19.jar' ||
                        it.name == 'simpledatabasemanager-1.0.jar' ||
                        it.name == 'lavaplayer.jar'
                    }
                    .collect { it.isDirectory() ? it : zipTree(it) }
        }
    }
}


// Example for how to get properties into the manifest for reading by the runtime..
jar {
    manifest {
        attributes([
            "Specification-Title": "examplemod",
            "Specification-Vendor": "examplemodsareus",
            "Specification-Version": "1", // We are version 1 of ourselves
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"examplemodsareus",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

// Example configuration to allow publishing using the maven-publish task
// This is the preferred method to reobfuscate your jar file
jar.finalizedBy('reobfJar')
// However if you are in a multi-project build, dev time needs unobfed jar files, so you can delay the obfuscation until publishing by doing
//publish.dependsOn('reobfJar')
configurations {
    shade
    shadow
    compile.extendsFrom shadow
    shadowMe { transitive = false }
}

build.dependsOn(shadowJar)

shadowJar {
    classifier ''
    project.configurations.shadow.setTransitive(true)
    setDescription("Shadow Jar")
    duplicatesStrategy 'exclude'
    configurations = [project.configurations.shadow]

    relocate 'org.apache.commons.collections4', 'fr.yan36.westerlife.repack.org.apache.commons.collections4'
    relocate 'org.apache.http.conn', 'fr.yan36.westerlife.repack.org.apache.http.conn'
    relocate 'org.apache.http.client', 'fr.yan36.westerlife.repack.org.apache.http.client'
    relocate "com.fasterxml.jackson", "fr.yan36.westerlife.repack.com.fasterxml.jackson"
    //relocate "org.json", "fr.yan36.westerliferepack.org.json"
    relocate "okio", "fr.yan36.westerlife.repack.okio"
    relocate "okhttp3", "fr.yan36.westerlife.repack.okhttp3"
    relocate "org.slf4j", "fr.yan36.westerlife.repack.org.slf4j"
    // repack lava-common
    relocate "com.sedmelluq", "com.sedmelluq"
}

reobf {
    shadowJar { }
}

jar.finalizedBy('reobfShadowJar')

/** Shit that idea needs to process resources ? **/
idea {
    module {
        inheritOutputDirs = true
    }
}
subprojects {
    apply plugin: 'idea'
}
task prepareAssets(type: Copy) {
    group = 'build'
    from project.file('src/main/resources')
    into project.file('build/classes/java/main')
}

classes.dependsOn(prepareAssets)
/** end of shit **/