# Set the default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G

# Don't use the Gradle daemon, as it can cause issues with Minecraft decompilation.
org.gradle.daemon=false